 public | actedin           | table    | olafur
 public | actors            | table    | olafur
 public | actors_id_seq     | sequence | olafur
 public | movies            | table    | olafur
 public | notendur          | table    | olafur
 public | notendur_id_seq   | sequence | olafur
 public | producers         | table    | olafur
 public | producers_id_seq  | sequence | olafur
 public | skraningar        | table    | olafur
 public | skraningar_id_seq | sequence | olafur
 public | users             | table    | olafur
 public | vidburdir         | table    | olafur
 public | vidburdir_id_seq  | sequence | olafur
